### ISSUE TITLE
The second game works does not appear on the display page

### ISSUE THREAD

**Issue by spaceack** [moonbitlang/MoonBit-Code-JAM-2024#43]
Hello, The [second game works](https://github.com/moonbitlang/MoonBit-Code-JAM-2024/tree/main/teams/CS%E8%B5%8F%E9%87%91%E7%8C%8E%E6%89%8B-%E4%BD%9C%E5%93%812) I pushed didn't appear on the display page

Pls how to fix it？

@bzy-debug

**Comment by spaceack** [comment]
Hello, The [second game works](https://github.com/moonbitlang/MoonBit-Code-JAM-2024/tree/main/teams/CS%E8%B5%8F%E9%87%91%E7%8C%8E%E6%89%8B-%E4%BD%9C%E5%93%812) I pushed didn't appear on the display page

Pls how to fix it？

@bzy-debug

**Comment by bzy-debug** [comment]
Thanks for bug report, should work now
